Add ignore default args option to roslaunch-check
plusone-robotics/ros_comm pull request #1
Opened 2019-07-25 15:41 UTC by collin-scribner

See https://github.com/ros/ros_comm/issues/953

Adds an option to roslaunch-check to ignore the error thrown when a `<arg>` is declared but doesn't have a default variable.

### Example
The example given in https://github.com/ros/ros_comm/issues/953 is as follows:
```
<launch>
  <arg name="foo" />     
  <node name="bar" pkg="bar" type="bar">
    <param name="foo" value="$(arg foo)" />
  </node>
</launch>
```

which, when run with roslaunch-check, will output 
```
$ rosrun roslaunch roslaunch-check foo.launch
FAILURE:
[foo.launch]:
	[foo.launch] requires the 'foo' arg to be set
```

The change adds an option to ignore this error with `-i` or `--ignore-default-args` like so
```
$ rosrun roslaunch roslaunch-check --ignore-default-args foo.launch
passed
```

2019-07-25 23:37 UTC, 130s commented
Looking into why Travis CI didn't get triggered for this PR. I see Travis is enabled https://travis-ci.org/plusone-robotics/ros_comm/settings

2019-07-25 23:42 UTC, 130s commented
> Looking into why Travis CI didn't get triggered for this PR. I see Travis is enabled https://travis-ci.org/plusone-robotics/ros_comm/settings

Ah, the origin repo doesn't use Travis (they use their Jenkins) for CI so there's no `.travis.yml`. I think we're fine for now (we might maintain this fork (which I'll open another discussion for). In that case I do suggest to enable CI).

2019-07-26 07:43 UTC, 130s requested changes
As I left an inline comment, the solution currently suggested looks possibly fragile to me. 

Also, some change suggestions:
- [check_roslaunch](https://github.com/ros/ros_comm/blob/17d8c67b6d79cd44d8c3f3675b77787ee93a2ddd/tools/roslaunch/src/roslaunch/rlutil.py#L183) is internally called from the check script, which seems to be the right place to add a change. In Python pkg where script and module are clearly separated like `roslaunch` for making modules reusable, changes should go to modules as much as possible.
- Unit test would be a great addition. Since you already referred to a minimum effective test case, it should be easily added.

That said, if the current suggested change is usable, I'm fine to move forward to merging and iterate over my suggestion (and other potential improvements).

2019-07-26 07:43 UTC, 130s commented on tools/roslaunch/scripts/roslaunch-check
> +            if re.compile('requires the \'.*\' arg to be set').search(error_msg):
Hmm. This depends on the exact log message string. So once the message string gets changed this check might stop working.

2019-07-26 07:43 UTC, 130s commented on tools/roslaunch/scripts/roslaunch-check
> +            if re.compile('requires the \'.*\' arg to be set').search(error_msg):
Hmm. This depends on the exact log message string. So once the message string gets changed this check might stop working.

2019-07-30 00:25 UTC, collin-scribner commented on tools/roslaunch/scripts/roslaunch-check
> +            if re.compile('requires the \'.*\' arg to be set').search(error_msg):
Refactored this in 558c09a, making it so that the conditional is closer to the try/except block that throws the original error so there's less risk of it breaking.

2019-07-31 02:22 UTC, 130s requested changes
Nice update! One more minor request posted.

2019-07-31 02:22 UTC, 130s commented on tools/roslaunch/test/xml/test-ignore-default-args.launch
> +<launch>
+1 for adding this. Now that a test case is added, let's add a call to roslaunch-check during test (i.e. this can likely be enabled in CMakeLists.txt).

2019-07-31 14:09 UTC, collin-scribner commented on tools/roslaunch/test/xml/test-ignore-default-args.launch
> +<launch>
Not sure what you mean by this. Python nosetests for the `test/unit` directory are already enabled in CMakeLists.txt?
```
if(CATKIN_ENABLE_TESTING)
  catkin_add_nosetests(test/unit)
endif()
```

2019-08-01 16:27 UTC, 130s commented on tools/roslaunch/test/xml/test-ignore-default-args.launch
> +<launch>
Have you confirmed the test you're adding gets executed?

```
  catkin_add_nosetests(test/unit)
```
Doesn't this run tests in `test/unit` directory only?

2019-08-01 17:47 UTC, collin-scribner commented on tools/roslaunch/test/xml/test-ignore-default-args.launch
> +<launch>
Yes, you can confirm the test runs with `nosetests -v test/unit/test_roslaunch_rlutil.py`. It references the "test-ignore-default-args.launch" file in a unit test of the check_roslaunch function in rlutil.

2019-08-01 18:33 UTC, 130s commented on tools/roslaunch/test/xml/test-ignore-default-args.launch
> +<launch>
Ah I see, I now found  you're adding a test case to an existing file `test_roslaunch_rlutil.py`. Nice.

2019-08-01 18:34 UTC, 130s approved these changes

2019-08-01 18:34 UTC, merged